### ISSUE TITLE
Property Accessor called with default value of property since 3.18.0

### ISSUE THREAD

**Issue by annervisser** [schmittjoh/serializer#1421]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no

Properties that have an Accessor setter, are called with the default property value whenever that class is deserialized

This is a BC break since 3.17.1. It happens since 3.18.0, specifically PR #1417

## Steps required to reproduce the problem
1. Take an example class with both traditional and promoted properties, some with accessors:
```php
class DefaultValuesAndAccessors
{
    public string $traditional = 'default';
    #[Accessor(setter: 'setTraditionalWithSetter')]
    public string $traditionalWithSetter = 'default';
    
    public function __construct(
        public string $promoted = 'default',
        #[Accessor(setter: 'setPromotedWithSetter')]
        public string $promotedWithSetter = 'default',
    ) {
    }

    public function setTraditionalWithSetter(string $value): void
    {
        $this->traditionalWithSetter = $value . '_fromsetter';
    }
    
    public function setPromotedWithSetter(string $value): void
    {
        $this->promotedWithSetter = $value . '_fromsetter';
    }
}
```
2. Deserialize some data into the class: `$serializer->fromArray([], DefaultValuesAndAccessors::class)`

Repo with reproduction: https://github.com/annervisser/jms-serializer-accessor-default-value-repro

## Expected Result
```json
{
    "traditional": "default",
    "traditionalWithSetter": "default",
    "promoted": "default",
    "promotedWithSetter": "default"
}
```

## Actual Result
output in 3.17.1:
```json
{
    "traditional": "default",
    "traditionalWithSetter": "default"
}
```

output in 3.18.0:
```json
{
    "traditional": "default",
    "traditionalWithSetter": "default_fromsetter",
    "promoted": "default",
    "promotedWithSetter": "default_fromsetter"
}
```

**Comment by joaojacome** [comment]
Hi @annervisser ,

Thank for the report. 

Would you be able to check if the pull request fixes your issue?

Thanks!

**Comment by annervisser** [comment]
> 

Yes, that PR should fix the issue :+1:
Thanks for the effort of putting my test case in as actual test :smile:

**Comment by eerison** [comment]
as I can see the PR was already merged, is it missing something else here?

**Comment by annervisser** [comment]
Nope, this should be fixed now in version https://github.com/schmittjoh/serializer/releases/tag/3.23.0 .

**Comment by eerison** [comment]
I'm still facing the same issue in release 3.23.0 :/ 

is it working for you on that version @annervisser ?

**Comment by eerison** [comment]
in my case this condition is making the output be different

https://github.com/schmittjoh/serializer/pull/1417/files#diff-b7efe8c51fe53a1f85923d4235bf2143baa4d3c3e998c063231f1969ec06c8aeR217-R219

**Comment by eerison** [comment]
@joaojacome why do you need to clone 

```
$propertyMetadata
```

do you remember?

**Comment by annervisser** [comment]
We were still facing an issue with `3.23.0`, so we're still running `3.17.1`.
Something to do with deserializationHandlers, we'll research this later & submit a proper issue.

But glad to hear it's fixed for you @eerison

**Comment by eerison** [comment]
> We were still facing an issue with `3.23.0`, so we're still running `3.17.1`. Something to do with deserializationHandlers, we'll research this later & submit a proper issue.
> 
> But glad to hear it's fixed for you @eerison

Yep, This issue was "fixed" (But we have a different output.)

But I'm also facing others issues
- https://github.com/schmittjoh/serializer/issues/1367
- https://github.com/schmittjoh/serializer/issues/1472
