### ISSUE TITLE
[3.20.0] The provided class "MyEnum" is an enum, and cannot be instantiated

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/serializer#1457]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no

I'm super grateful for the work on enums in https://github.com/schmittjoh/serializer/pull/1448. I'm just testing it out with `jms/serializer v3.20.0` together with [`jms/serializer-bundle dev-enable-enum`](https://github.com/schmittjoh/JMSSerializerBundle/pull/915) and noticed something wrong.

## Steps required to reproduce the problem

```php
enum SocialPlatform : string
{
    case Spotify = 'spotify';
    case Instagram = 'instagram';
}

class MyEvent {
    public function __construct(
        private int $userId,
        private SocialPlatform $socialPlatform,
    ) {
    }
}

$object = new MyEvent(1, SocialPlatform::instagram);

// This is in a functional test, using Symfony Bundle, with `enum_support` enabled.
$this->serializer = self::getContainer()->get('jms_serializer');

$this->context = SerializationContext::create()
    ->enableMaxDepthChecks()
    ->setSerializeNull(true);

$serialized = $this->serializer->serialize($object, 'json', $this->context);
// serializes to: {"user_id":1,"social_platform":"instagram"}

$deserialized = $this->serializer->deserialize($serialized, MyEvent::class, 'json');
// fails Doctrine\Instantiator\Exception\InvalidArgumentException : The provided class "SocialPlatform" is an enum, and cannot be instantiated
```

## Expected Result

No error, deserialized back to an object.

## Actual Result

```
Doctrine\Instantiator\Exception\InvalidArgumentException : The provided class "SocialPlatform" is an enum, and cannot be instantiated
 /Volumes/CS/www/app/vendor/jms/serializer/src/Construction/UnserializeObjectConstructor.php:22
 /Volumes/CS/www/app/vendor/jms/serializer/src/Construction/DoctrineObjectConstructor.php:72
 /Volumes/CS/www/app/vendor/jms/serializer/src/GraphNavigator/DeserializationGraphNavigator.php:189
 /Volumes/CS/www/app/vendor/jms/serializer/src/JsonDeserializationVisitor.php:188
 /Volumes/CS/www/app/vendor/jms/serializer/src/GraphNavigator/DeserializationGraphNavigator.php:214
 /Volumes/CS/www/app/vendor/jms/serializer/src/JsonDeserializationVisitor.php:112
 /Volumes/CS/www/app/vendor/jms/serializer/src/GraphNavigator/DeserializationGraphNavigator.php:140
 /Volumes/CS/www/app/vendor/jms/serializer/src/JsonDeserializationVisitor.php:188
 /Volumes/CS/www/app/vendor/jms/serializer/src/GraphNavigator/DeserializationGraphNavigator.php:214
 /Volumes/CS/www/app/vendor/jms/serializer/src/Serializer.php:252
 /Volumes/CS/www/app/vendor/jms/serializer/src/Serializer.php:180
```

**Comment by goetas** [comment]
https://github.com/schmittjoh/JMSSerializerBundle/pull/915#issuecomment-1375348012 related

**Comment by ruudk** [comment]
@goetas Now that that PR is merged, is it fixed? I didn't test yet.

**Comment by goetas** [comment]
it should be. can you verify?
you need this release of the bundle https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/5.2.0

**Comment by ruudk** [comment]
I have the latest version of both packages. The problem is still there.

I think the issue is related to DoctrineObjectConstructor.php:72 not supporting enums yet.

**Comment by ruudk** [comment]
I verified that `\JMS\Serializer\Handler\EnumHandler::serializeEnum` is called upon serialization. But in deserialization, it never calls `\JMS\Serializer\Handler\EnumHandler::deserializeEnum`

**Comment by ruudk** [comment]
On serialization, it calls `\JMS\SerializerBundle\Debug\TraceableHandlerRegistry::getHandler` with `$typeName = 'enum'`.

On deserialization, it calls the `getHandler` again but this time, the `$typeName = 'FQCN\ToTheEnum'`

**Comment by ruudk** [comment]
When I manually type it does work properly:
```php
class MyEvent {
    public function __construct(
        private int $userId,
        #[Type("enum<'SocialPlatform', 'value'>")]
        private SocialPlatform $socialPlatform,
    ) {
    }
}
```

**Comment by ruudk** [comment]
I think that the `$typeName` of an enum should always become `enum` with additionally the `fqcn`. Then deserialization becomes easier, as it's not confused with normal objects.

**Comment by goetas** [comment]
You are right, I totally forgot about the de serializeation listener 😭😭

**Comment by ruudk** [comment]
It can happen. Do you have time to add it? Or do you want me to try it?

**Comment by goetas** [comment]
I will not have time this morning, probably in the evening. If you want to try it will be certainly helpful

**Comment by ruudk** [comment]
I'm having a hard time understanding where the problem is. Because when I check the [JsonSerializationTest](https://github.com/schmittjoh/serializer/blob/master/tests/Serializer/JsonSerializationTest.php) I see that it already provides a lot of tests for enums. And that [BaseSerializationTest::testEnum](https://github.com/schmittjoh/serializer/blob/0fa5e4f332fdce524aef5e5d4572d98d30168437/tests/Serializer/BaseSerializationTest.php#L360-L376) also tests deserialization. 

That just passes fine.

So I suspect there is something wrong with JMSSerializerBundle. As that is what I'm using.

**Comment by ruudk** [comment]
Maybe the problem is that the Subscriber only changes the typeName to `enum` on `serializer.pre_serialize`. But that this type should be stored in the metadata (and cached). Because when I set a breakpoint in `TraceableMetadataFactory::getMetadataForClass` I see that when it loads `MyEvent`, the `$socialPlatform` has `PropertyMetadata` with `$type` set to `[name: 'SocialPlatform`, params: []]`.

**Comment by ruudk** [comment]
Caused by https://github.com/schmittjoh/serializer/blob/0fa5e4f332fdce524aef5e5d4572d98d30168437/src/Metadata/Driver/TypedPropertiesDriver.php#L120-L121 because `class_exists(SocialPlatform)` returns `true` 😊

**Comment by ruudk** [comment]
PR incoming!

**Comment by goetas** [comment]
@ruudk the fix is available in https://github.com/schmittjoh/JMSSerializerBundle/pull/919 could you please test it? cc @simPod @sasezaki

**Comment by goetas** [comment]
@scyzoryck  I think it addresses https://github.com/schmittjoh/serializer/pull/1463 as well, what do you think?

**Comment by ruudk** [comment]
Just tested it, still not working. https://github.com/schmittjoh/JMSSerializerBundle/pull/919#issuecomment-1415216916

**Comment by ruudk** [comment]
Don't understand why this is closed as I tested the PR and said it was not working.

**Comment by goetas** [comment]
I'm sorry, I missed that, 😞

**Comment by ruudk** [comment]
Tried it again today, and it seems to be working fine. Thank you! 💙
