### ISSUE TITLE
I'm receiving "Class ArrayCollection does not exist" when serializing (temporarily solved with a workaround)

### ISSUE THREAD

**Issue by stephenfrank** [schmittjoh/serializer#274]
I saw another issue ticket covering this but the thread included so many topics that didn't help me solve or debug the issue.

I'm receiving this exception when serializing a class with nested collections:

```
Class ArrayCollection does not exist

27. ReflectionException
…/­vendor/­jms/­metadata/­src/­Metadata/­MetadataFactory.php:167
```

... and I debugged and breakpointed myself to death and eventually found the code arriving at this point:

`JMS\Serializer\EventDispatcher\Subscriber\DoctrineProxySubscriber`

``` php
// If the set type name is not an actual class, but a faked type for which a custom handler exists, we do not
// modify it with this subscriber. Also, we forgo autoloading here as an instance of this type is already created,
// so it must be loaded if its a real class.
$virtualType = ! class_exists($type['name'], false);

if ($object instanceof PersistentCollection
    || $object instanceof MongoDBPersistentCollection
    || $object instanceof PHPCRPersistentCollection
) {
    if ( ! $virtualType) {
        $event->setType('ArrayCollection');
    }

    return;
}
```

For anyone who needs to solve this in a hurry and move on with their day, adding this to your bootstrapping/config file will give PHP a chance to find the class:

``` php
class_alias('Doctrine\Common\Collections\ArrayCollection', 'ArrayCollection');
```

Is there any more reasonable way to solving this?

**Comment by LeoBenoist** [comment]
+1

**Comment by LeoBenoist** [comment]
Lets go for some extend...:

```yml
parameters:
    jms_serializer.datetime_handler.class: YourBundle\Serializer\DateHandler
```

```php
<?php

namespace YourBundle\Serializer;

use JMS\Serializer\GraphNavigator;
use JMS\Serializer\Handler\DateHandler as BaseDateHandler;

class DateHandler extends BaseDateHandler
{
    /**
     * @return array
     */
    public static function getSubscribingMethods()
    {
        $methods = [];
        $types   = ['DateTime', 'DateInterval'];

        foreach (['json', 'xml', 'yml', 'array'] as $format) {
            $methods[] = [
                'type'      => 'DateTime',
                'direction' => GraphNavigator::DIRECTION_DESERIALIZATION,
                'format'    => $format,
            ];

            foreach ($types as $type) {
                $methods[] = [
                    'type'      => $type,
                    'format'    => $format,
                    'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                    'method'    => 'serialize'.$type,
                ];
            }
        }

        return $methods;
    }
}
```
And a simple array serializer

```yml
you.array_serialization_visitor:
        class: YourBundle\Serializer\ArraySerializationVisitor
        arguments:
           - @jms_serializer.naming_strategy
        tags:
           - { name: jms_serializer.serialization_visitor, format: array}
```

```php
<?php

namespace YourBundle\Serializer;

use JMS\Serializer\GenericSerializationVisitor;

class ArraySerializationVisitor extends GenericSerializationVisitor
{
    /**
     * @return array
     */
    public function getResult()
    {
        return $this->getRoot();
    }
}
```

**Comment by goetas** [comment]
can it be related to https://github.com/schmittjoh/serializer/issues/517#issuecomment-237240517 ?

**Comment by bartosz-zolynski** [comment]
I'm using JMS Serializer with Slim 3 framework for groups so I can easily return the response with desired fields. In this case there's no purpose to encode the result to json in the serializer using "json" method as if I want to attach it to the `Slim\Http\Response` (PSR-7) using:
```
$response = $response->withJson($responseData, $responseHttpCode);
```
then I need to decode it, as it will be encoded in `Response::withJson()` method again. Performance can suffer for bigger objects as data has been encoded twice, and decoded once, and it obviously makes no sense. In my opinion, `ArraySerializationVisitor` (or as I called it, `ObjectSerializationVisitor`) should be one of default visitors, and actually this array of methods available, it should be extendable, or - if not - then should be available to retrieve from the single method rather than spread through variety of handlers in `getSubscribingMethods()` method (if I'm understanding the purposes of it clearly, but I can be wrong here).

JMS Serializer is really powerful, and I prefer to overwrite "json" method as mentioned above to get the desired result. Actually I was trying to play with PSR-7 StreamInterface thingy, but I still can't get it really (I end up with errors that I can't write to stream, or other weird issues) so actually I don't know how to set the part of the body in other way than by using `withJson()` for Slim's Response which implements PSR-7 standard.

**Comment by goetas** [comment]
Does your application include `doctine/common` ?

**Comment by goetas** [comment]
fixed with https://github.com/schmittjoh/serializer/commit/c8ad292e2f8b716180cc122ddb3e9b5fd82008db

**Comment by naitsirch** [comment]
@goetas In my case `doctrine/common` and `doctrine/collections` is installed, but I still get this error, after upgrading the serializer to `1.10.0`.

**Comment by naitsirch** [comment]
I found out, that this error happened in my case because of FriendsOfSymfony/FOSRestBundle#1851
