### ISSUE TITLE
problems with xml namespaces after update

### ISSUE THREAD

**Issue by moinomedia** [schmittjoh/serializer#621]
i use jms/serializer to deserialize xml files to dto. After updating serializer via composer i have some problems with my project. 

i have properties which are defined in a xml namespace and others that are not defined in a namespace. For example

```xml
<abc:myProperty>
```
or

```xml
 <aPropertyWithoutNamespace>
```

before update there was no problem to deserialize properties without namespace. now it seems that i must explicit define a namespace, otherwise the property will not be mapped. 

To make things more clear.

Before update the following works fine:

```php
/**
* @JMS\SerializedName("myProperty")
* @JMS\Type("string")
* @JMS\XmlElement(cdata=false)
*/
private $myProperty;
```

After update i have to define a namspace to get a mapped property. Like this.

```php
/**
* @JMS\SerializedName("myProperty")
* @JMS\Type("string")
* @JMS\XmlElement(cdata=false, namespace="http://a.namespace.com")
*/
private $myProperty;
```

What i am doing wrong?

Please let me know, if you need more details.

Thanks Nico

**Comment by goetas** [comment]
Hi, any chance to create a failing test case?

**Comment by goetas** [comment]
What makes "myProperty" a namespaced element? is it contained in a namespaced one?
```
/**
* @JMS\SerializedName("myProperty")
* @JMS\Type("string")
* @JMS\XmlElement(cdata=false)
*/
private $myProperty;
```

**Comment by moinomedia** [comment]
I defined a class like this. 

/**
 * Class MyClass
 *** @JMS\XmlNamespace(uri="http://www.abc.de/xml/data/1.0")**
 * @JMS\XmlNamespace(prefix="ebd", uri="http://www.abc.de/xml/data_ebd/definitionen/1.0")
 * @JMS\XmlNamespace(prefix="ebs", uri="http://www.dbenergie.de/data_ebs/bla/structure/nachrichtenstrukturdefinitionen/1.0")
 */
class MyClass extends BaseClass

in MyClass i have property

/**
     * @JMS\SerializedName("myProp")
     * @JMS\Type("string")
     * @JMS\XmlElement(cdata=false)
     */
    private $myProp;

Before update the property was mapped correctly. But now i have to redefine the namspace
http://www.abc.de/xml/data/1.0 for the property $myProp to get mapped data.

/**
     * @JMS\SerializedName("myProp")
     * @JMS\Type("string")
     * @JMS\XmlElement(cdata=false, namespace="http://www.abc.de/xml/data/1.0 ")
     */
    private $myProp;

**Comment by moinomedia** [comment]
Was this information more usefull?

**Comment by goetas** [comment]
can you do some formatting to your comment?

> Hi, any chance to create a failing test case?

**Comment by moinomedia** [comment]
yes ;) give me some minutes

**Comment by moinomedia** [comment]
done. i hope it is better now. sorry ;)

**Comment by moinomedia** [comment]
i think i found the problem, but i am no sure. the xml files contains different prefixes for the same structure. for example ns1 instead of abc and revert. so maybe this is the reason for my problem. 
i think this issue is specific to my domain an not a common error. 

thank you for your fast response. i will close this issue

**Comment by goetas** [comment]
In case the problem persists, feel fee to open the issue again.

**Comment by moinomedia** [comment]
thank you :)
